export const MAX_RECORDING_MS = 30000;
export const DEFAULT_WAVEFORM_SAMPLE_INTERVAL_MS = 200;
export const WAVEFORM_DISPLAY_SCALE = 120;
export const WAVEFORM_BAR_GAP = 1;
export const WAVEFORM_HORIZONTAL_PADDING = 10;
export const WAVEFORM_BORDER_WIDTH = 1;
export const STATIC_WAVEFORM_TARGET_BARS = Math.ceil(
  MAX_RECORDING_MS / DEFAULT_WAVEFORM_SAMPLE_INTERVAL_MS,
);
